name: Deploy AWS Lambda

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID: {required: true}
      AWS_SECRET_ACCESS_KEY: {required: true}
      AWS_REGION: {required: true}
      AWS_LAMBDA_BACKEND_FUNCTION_NAME: {required: true}
      AWS_LAMBDA_WEBSOCKET_FUNCTION_NAME: {required: true}
      AWS_LAMBDA_ARTIFACTS_BUCKET: {required: true}

jobs:
  deploy-backend:
    name: Deploy Backend Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.AWS_LAMBDA_BACKEND_FUNCTION_NAME }}" \
            --s3-bucket "${{ secrets.AWS_LAMBDA_ARTIFACTS_BUCKET }}" \
            --s3-key "flowboard-backend-${{ github.sha }}.jar"
          aws lambda wait function-updated --function-name "${{ secrets.AWS_LAMBDA_BACKEND_FUNCTION_NAME }}"

  deploy-websocket:
    name: Deploy WebSocket Lambda
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.AWS_LAMBDA_WEBSOCKET_FUNCTION_NAME }}" \
            --s3-bucket "${{ secrets.AWS_LAMBDA_ARTIFACTS_BUCKET }}" \
            --s3-key "flowboard-backend-${{ github.sha }}.jar"
          aws lambda wait function-updated --function-name "${{ secrets.AWS_LAMBDA_WEBSOCKET_FUNCTION_NAME }}"